# Parsing Constants
cdef int ORD_N, ORD_R, ORD_T, ORD_TAB, ORD_SPACE, ORD_NEWLINE, \
         ORD_CARRIAGE_RETURN, ORD_MINUS, ORD_NUMBER_0, ORD_NUMBER_9, \
         ORD_BACKSLASH, ORD_DOUBLE_QUOTE, ORD_OPEN_BRACKET, \
         ORD_CLOSE_BRACKET

cdef char *STR_MINUS
